Import libraries/ dependencies

In [3]:
from sklearn.datasets import load_files
from keras.utils import np_utils
import numpy as np
from glob import glob

Import images

In [22]:
def load_train (path):
    data=load_files(path)
    driver_file=np.array(data['filenames'])
    driver_target=np_utils.to_categorical(np.array(data['target']),10)
    return driver_file,driver_target

def load_test(path):
    data=load_files(path)
    driver_file=np.array(data['filenames'])
    return driver_file


train_files,train_targets = load_train('Data/imgs/train')
test_files = load_test('Data/imgs/test')



Data Analysis

In [23]:

print(len(train_targets))
print('test files %d number of images' % len(test_files))
print('test targets size %d' % len(test_files))
for p in train_targets[:5]: print (p)
for q in train_files[:5]: print(q)

22424
test files 0 number of images
test targets size 0
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
[ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
Data/imgs/train\c9\img_54.jpg
Data/imgs/train\c1\img_94750.jpg
Data/imgs/train\c9\img_90465.jpg
Data/imgs/train\c3\img_89554.jpg
Data/imgs/train\c5\img_13547.jpg


Pre-process data

Image Enhancements

Model Architecture

Model Compilation

Model Training

Model Testing

Model results